# Generated by Django 5.1.1 on 2024-11-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_product_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
