# Generated by Django 5.1.1 on 2024-12-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_url',
            field=models.CharField(max_length=1000),
        ),
    ]
